added null check to fix wrong .merge which is causing was causing bug TypeError: Cannot convert undefined or null to object
added null check to fix wrong .merge which is causing was causing bug TypeError: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
2023-01-13 23:01:89 [oas-tools] ERROR: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at _getParameterValue (file:///Users/acoder/Documents/GitHub/login-service/node_modules/@oas-tools/core/src/middleware/native/oas-params.js:93:36)
    at file:///Users/acoder/Documents/GitHub/login-service/node_modules/@oas-tools/core/src/middleware/native/oas-params.js:27:78